# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  basic-checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - run: npm ci
    - run: npm run lint
    - run: npm run unittest

  build-vscode-extension:

    needs: basic-checks

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - run: npm ci
    - run: npm run pack
    - name: Upload vscode-extension artifact
      uses: actions/upload-artifact@v3
      with:
        name: vscode-extension
        path: ucx*.vsix

  build-cli-tool:

    needs: basic-checks

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'

    - run: npm ci
    - run: npm run esbuild-ucx
    - name: Upload cli-tool artifact
      uses: actions/upload-artifact@v3
      with:
        name: cli-tool
        path: ./out/ucx.js

  test-cli-tool:

    needs: build-cli-tool

    runs-on: ubuntu-latest

    strategy:
      matrix:
        utversion: [469b, 469a, 451b]
        include:
          - utversion: 469b
            repo: https://github.com/Slipyx/UT99.git
            commit: 769bd788cb2c06077a26ff7c3e4fced521a2169e
          - utversion: 469a
            repo: https://github.com/Slipyx/UT99.git
            commit: f2ebd703845075a2d667e8e3f2f71a5e7f187610
          - utversion: 451b
            repo: https://github.com/Slipyx/UT99.git
            commit: a26a3359704873df5a24d0b241a32ca5fc36a8b7

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: cli-tool
      - run: ls
      - run: node ucx.js version
      - run: git clone ${{ matrix.repo }} --no-checkout ut
      - run: cd ut && git checkout ${{ matrix.commit }}
      - run: node ucx.js lint ut --quiet
